### ISSUE TITLE
variable name "frequencies" is misleading

### ISSUE THREAD

**Issue by jounathaen** [madmax28/aoc2018#1]
The name "frequencies" in https://github.com/madmax28/aoc2018/blob/2e87e39f15d16256edb210c597e9d09794a69556/day3/src/main.rs#L45
is misleading.
I'd suggest to rename it to something like "fabric"

**Comment by madmax28** [comment]
The vec holds the frequency of claims for a position on the fabric. It doesn't represent the fabric itself.
Anyway, maybe something like `claim_cnt` would be clearer? Feel free to send a PR. Closing this.
